### PR TITLE
65 Check seat limit when enrolling existing users

### PR DESCRIPTION
**Pull request by leonstr**
Prevously there was only a check for available seats when creating users, if the user already existed but was not enrolled they could access the course even when the seat limit had been reached.  Now available seats are checked when creating new users or enrolling existing users.

### CODE REVIEW

**Comment by andrewhancox** [comment]
Has any thought been given to integrating this fix?

**Comment by bwalkerl** [comment]
Thanks @leonstr 

Apologies for the slow response, ~~but this looks good to me once the conflict has been resolved~~.

One issue in the conflict is that the newly added new_seat_allocated event will also be incorrect. Are you also able to add a fix for that? If not, I'm happy to merge this if it's placed inside the user check to replicate current behavior, and for a separate issue to be raised.

**Comment by bwalkerl** [comment]
Actually on second thoughts it may be possible for a student to be apart of multiple courses within a subscription/tier and only take up one slot. This behavior needs to be confirmed, but if that's the case there may need to be a more specific check.

**Comment by leonstr** [comment]
I'm not currently working with mod_scormremote so I'm unlikely to do any further work on this for the foreseeable future.

**Comment by bwalkerl** [comment]
Closing this off as I believe https://github.com/catalyst/moodle-mod_scormremote/pull/80/commits/3d8f66316ce27c2c168281b9c9a7f3e8db1d6474 should have resolved this.

**Pull request closed without merging**
