### PR TITLE
Fix security issue: Check user CM visibility

### PR DESCRIPTION
**Pull request by andrewhancox**
Currently the plugin will still load data where the activity or course are hidden or pending deletion.

### CODE REVIEW

**Comment by andrewhancox** [comment]
Has any thought been given to integrating this fix?

**Comment by andrewhancox** [comment]
Any thoughts about integrating this?

**Comment by bwalkerl** [comment]
Thanks @andrewhancox 

Apologies again on the delay. I'll get around to testing and merging this shortly. 

Just like the missing manual enrolment error, I think it would be good if this also triggered a remote_view_error event to add this to the logs for more visibility.

**Comment by andrewhancox** [comment]
Done - that event didn't exist when I first raised this PR...

**Comment by bwalkerl** [comment]
Thanks again for your work on this @andrewhancox 

I ended up cherry-picking this into https://github.com/catalyst/moodle-mod_scormremote/pull/70 to resolve the conflicts and clean up CI to get it merged together with the other similar features. This has now been merged so I'm closing this off.

**Pull request closed without merging**
